Controllers/FramesController.cs
using Kamenici.Data;
using Kamenici.Models;
using Kamenici.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
namespace Kamenici.Controllers
{
    public class FramesController : Controller
    {
        private IFramesRepository _framesRepository;
        private readonly UserManager<IdentityUser> userManager;
        public FramesController(IFramesRepository framesRepository, UserManager<IdentityUser> userManager)
        {
            _framesRepository = framesRepository;
            this.userManager = userManager;
        }
        [HttpGet] 
        public IActionResult CreateFrame()
        {
            ViewBag.Today = DateOnly.FromDateTime(DateTime.Today);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateFrame(CreateFrameViewModel model)
        {
            var username = HttpContext.User.Identity.Name;
            var createdbyid = userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;
            if (ModelState.IsValid)
            {
                Frame frame = new Frame(model.Width, model.Height, model.Price, createdbyid);
                _framesRepository.Add(frame);
            }
            return RedirectToAction("AllFrames");
        }
        [HttpGet]
        public ViewResult AllFrames()
        {
            var model = _framesRepository.getAllFrames();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> EditFrame(int frameid)
        {
            var frame = _framesRepository.getFrame(frameid);
            if (frame == null)
            {
                ViewBag.ErrorMessage = $"Frame with Id = {frameid} cannot be found";
                return View("NotFound");
            }
            var model = new EditFrameViewModel
            {
                FrameId = frame.FrameId,
                Width = frame.Width,
                Height = frame.Height,
                Available = frame.Available.HasValue ? frame.Available.Value : false,
                Price = frame.Price,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditFrame(EditFrameViewModel model)
        {
            var frame = _framesRepository.getFrame(model.FrameId);
            if(frame == null)
            {
                ViewBag.ErrorMessage = $"Frame with Id = {model.FrameId} cannot be found";
                return View("NotFound");
            } else
            {
                frame.Width= model.Width;
                frame.Height= model.Height;
                frame.Available= model.Available;
                frame.Price= model.Price;
                var result = _framesRepository.Update(frame);
                if (result != null)
                {
                    return RedirectToAction("AllFrames");
                }
                return View(model);
            }
        }
        [HttpGet]
        public async Task<IActionResult> DeleteFrame(int frameId)
        {
            if(frameId == null)
            {
                return View("NotFound");
            }

            var frame = _framesRepository.getFrame(frameId);
            if(frame == null)
            {
                return View("NotFound");
            }
            var model = new DeleteFrameViewModel
            {
                FrameId = frameId,
                Available = frame.Available.HasValue ? frame.Available.Value : false,
                Price = frame.Price,
                Height = frame.Height,
                Width = frame.Width
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int frameId)
        {
            _framesRepository.Delete(frameId);
            return RedirectToAction("AllFrames");
        }
    }
}

Controllers/OrdersController.cs
using Kamenici.Data;
using Kamenici.Models;
using Kamenici.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Kamenici.Controllers
{
    public class OrdersController : Controller
    {
        private IOrdersRepository _ordersRepository;
        private readonly UserManager<IdentityUser> userManager;
        private IFramesRepository _framesRepository;
        public OrdersController(IOrdersRepository ordersRepository, UserManager<IdentityUser> userManager, IFramesRepository framesRepository)
        {
            _ordersRepository = ordersRepository;
            this.userManager = userManager;
            _framesRepository = framesRepository;
        }

        public ViewResult AllOrders()
        {
            var model = _ordersRepository.GetAllOrders();
            return View(model);
        }
        [HttpGet]
        public IActionResult CreateOrder(int FrameId)
        {
            var model = new CreateOrderViewModel(FrameId);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> CreateOrder(CreateOrderViewModel model)
        {
            var username = HttpContext.User.Identity.Name;
            var createdbyid = userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;
            if (ModelState.IsValid)
            {
                Order order = new Order(model.FrameId, model.DueDate, createdbyid);
                _ordersRepository.Add(order);
            }
            return RedirectToAction("MyOrders");
        }
        [HttpGet]
        public async Task<IActionResult> NewOrder()
        {
            var model = _framesRepository.getAllFrames();
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> EditOrder(int orderid)
        {
            var order = _ordersRepository.GetOrder(orderid);
            if(order == null)
            {
                ViewBag.ErrorMessage = $"Frame with Id = {orderid} canot be found";
                return View("NotFound");
            }
            var model = new EditOrderViewModel
            {
                OrderId = order.OrderId,
                OrderDate = order.DueDate,
                DueDate = order.DueDate,
                Status = order.Status,
                FrameId = order.FrameId,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditOrder(EditOrderViewModel model)
        {
            var order = _ordersRepository.GetOrder(model.OrderId);
            if(order == null)
            {
                ViewBag.ErrorMessage = $"Order with Id = {model.OrderId} cannot be found";
                return View("NotFound");
            } else
            {
                order.Status = model.Status;
                order.DueDate = model.DueDate;
                order.OrderDate = model.OrderDate;
                model.FrameId = order.FrameId;
                var result = _ordersRepository.Update(order);
                if(result != null)
                {
                    return RedirectToAction("AllOrders");
                }
                return View(model);
            }
           
        }
        [HttpGet]
        public async Task<IActionResult> DeleteOrder(int orderId)
        {
            if(orderId == null)
            {
                return View("NotFound");
            }
            var order = _ordersRepository.GetOrder(orderId);
            if(order == null)
            {
                return View("NotFound");
            }
            var model = new DeleteOrderViewModel
            {
                OrderId = orderId,
                DueDate = order.DueDate,
                FrameId = order.FrameId,
                OrderDate = order.OrderDate,
                Status = order.Status,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int orderId)
        {
            _ordersRepository.Delete(orderId);
            return RedirectToAction("AllOrders");
        }
        public ViewResult MyOrders()
        {
            var allorders = _ordersRepository.GetAllOrders();
            var username = HttpContext.User.Identity.Name;
            var createdbyid = userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Id;
            var model = new List<Order>();
            foreach (var order in allorders)
            {
                if(order.CreatedBy == createdbyid)
                {
                    model.Add(order);
                }
            }
            return View(model);
        }
    }
}

Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}
<h1>@ViewBag.ErrorMessage</h1>
<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kamenici</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kamenici.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img height="80" width = "140" src="https://scontent-frt3-1.xx.fbcdn.net/v/t1.6435-9/65250739_400928733853937_7378551959655022592_n.png?_nc_cat=104&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=AzmUpiXDuzQAX-9XP8V&_nc_ht=scontent-frt3-1.xx&oh=00_AT_vsuurE1N3LzjiTBinH7kopucw0JSWPekXHMGy9ytVuQ&oe=61FA3988"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="ListRoles">All Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Frames" asp-action="AllFrames">All Frames</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="AllOrders">All Orders</a>
                            </li>
                            }
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (!User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="NewOrder">New Order</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="MyOrders">My Orders</a>
                                </li>
                            }
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Kamenici
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>